# Generated by Django 5.1 on 2024-08-26 08:24

import markdownx.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/images', verbose_name='イメージ写真')),
                ('meta_keywords', models.CharField(max_length=155, verbose_name='メタキーワード')),
                ('meta_description', models.TextField(verbose_name='メタ説明文')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', markdownx.models.MarkdownxField(verbose_name='本文')),
                ('viwes', models.PositiveIntegerField(default=0, verbose_name='閲覧数')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開済')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='作成日時')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '記事',
            },
        ),
    ]
