# Generated by Django 5.1 on 2024-08-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='viwes',
            new_name='views',
        ),
    ]
